### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by lj322** [Piggered/MakeLobbiesEvenBetter#1]
"Unhandled exception has occured in your application. If you click continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately. Object reference not set to an instance of an object.

**Comment by Piggered** [comment]
Heyo, I'd need more details for this. Does this occur while you're using the program or does it do that at startup?

**Comment by lj322** [comment]
it occurs as soon as I try and open the program. When I click continue it just continues to show that msg when I use any of the toolbox options. Its also showing me this now as well
![open](https://user-images.githubusercontent.com/54820378/64147155-6eb7e700-cded-11e9-82f9-722cbe975852.png)

**Comment by Piggered** [comment]
This error most likely means that you have improperly extracted the ZIP archive; the program couldn't find _Newtonsoft.Json.dll_. Are you sure you properly unzipped the archive?

If you don't know what I'm talking about, here a general step-by-step guide for MLEB:

1. Be sure you downloaded the right file. You should have downloaded the "MLEB_x.x.x.zip" file in the [Releases](https://github.com/Piggered/MakeLobbiesEvenBetter/releases) section of this repository by clicking on it.
2. Open the ZIP file and extract the content, which is the _MakeLobbiesEvenBetter_ folder in the ZIP archive. You can do so by dragging the _MakeLobbiesEvenBetter_ folder to somewhere you're going to remember (for example, your desktop), just like the screenshot below.
![ZIP extraction screenshot](https://i.piggered.me/u/n4em9.png)
3. Close _MLEB_x.x.x.zip_ and open_ the _MakeLobbiesEvenBetter_ folder from where you just extracted it to. The content of that folder should look like the screenshot below. **Do NOT move or delete any of the files inside that folder; they are important for the program.**
![Folder content screenshot](https://i.piggered.me/u/59df4.png)
4. Run _MakeLobbiesEvenBetter.exe_ (or simply _MakeLobbiesEvenBetter_ if you have known extensions hidden on your computer), and the program should open and work properly.

**OPTIONAL:** If you want to have an icon for the program without the other files, create a shortcut by doing the following:

1. Move the _MakeLobbiesEvenBetter_ **folder** to wherever you want (you won't need to access the folder after you've done everything properly).
2. Open the folder from wherever you moved _MakeLobbiesEvenBetter_.
3. Right-click _MakeLobbiesEvenBetter.exe_ (or  _MakeLobbiesEvenBetter_) and click "Create shortcut", just like in the screenshot below.
![Creating a shortcut screenshot](https://i.piggered.me/u/szw0h.png)
4. This should create a file named "MakeLobbiesEvenBetter.exe - Shortcut". Feel free to rename or move it to anything or/and anywhere you want. This will be the file you will run in order to open the program from now on.

Please note that if you move the _MakeLobbiesEvenBetter_ folder after you've created the shortcut, you're going to have to create another shortcut.

If you need assistance on anything else, or if this doesn't work, you can continue replying to this thread. For now I'll be closing this issue.
