### ISSUE TITLE
DBD Det servers broke MLEB

### ISSUE THREAD

**Issue by Demidevimon** [Piggered/MakeLobbiesEvenBetter#2]
Yeah as soon as they started using the dedicated servers In the start of October.
Mleb no longer works as intended.

**Comment by Piggered** [comment]
Yeah, unfortunately with the way MLEB works, it cannot work with dedicated servers, as the match host is the server, and not the killer anymore. MLEB is only able to capture the host of the match, which is why MLEB works in peer-to-peer.

This means that whenever they roll out dedicated servers, MLEB will no longer work. When it's fully released, the only thing I can do is archive the repository. Sorry.
